CIRCUITPY_WIFI_SSID = "YOUR_SSID"
CIRCUITPY_WIFI_PASSWORD = "YOUR_PASSWORD"
IFTTT_URL = "https://maker.ifttt.com/trigger/{YOUR_EVENT_NAME}/with/key/"
IFTTT_KEY = "YOUR WEB REQUESTS KEY"

# NOT NECCESSARY
CIRCUITPY_WEB_API_PORT = 80
CIRCUITPY_WEB_API_PASSWORD="ANY_PASSWORD"
